### ISSUE TITLE
I cant use this extension..

### ISSUE THREAD

**Issue by nightynight99** [muratalperen/GoogleFormsAutoFiller#4]
hi, it still available? i cant use it
i already focus and press space but it not working.

![image](https://user-images.githubusercontent.com/101282231/157498126-3b7b2103-76cc-4b6b-8687-f64fbef9f710.png)

**Comment by njmlvr** [comment]
i cant use it too :( ive emailed the developer but im not sure when will they fix it

**Comment by njmlvr** [comment]
hello there! so sorry but I want to inform you that i still can't use the
extension :( i've reinstalled the extension but I still can't use it :(

**Comment by nightynight99** [comment]
> i cant use it too :( ive emailed the developer but im not sure when will they fix it

hi! now i can use it!! do you install new file? i reinstall from code in build and add extension in chrome

**Comment by njmlvr** [comment]
hiii, aaa how do you do it? i mean how do you install the new file from the
code in build? 😭 i dont know howw

**Comment by nightynight99** [comment]
yess i download from this 
![image](https://user-images.githubusercontent.com/101282231/158155555-3b8f2713-4015-4757-9390-323dae2e92a9.png)

and click load unpacked (you must to open dev mode on top-right)
link : chrome://extensions/

![image](https://user-images.githubusercontent.com/101282231/158155666-6705540d-e9a1-4081-8fd0-f9deb602cac3.png)

so, you click folder you export file and add this. it have a error so you must to delete it
![image](https://user-images.githubusercontent.com/101282231/158156156-00e2b845-dc71-40cc-be7c-77be09a354bb.png)

finished! 
![image](https://user-images.githubusercontent.com/101282231/158156254-541c6f00-aa1c-4e3e-8683-045e2b2df6d8.png)
![image](https://user-images.githubusercontent.com/101282231/158156591-c99cdd54-7e44-4716-acc5-1ff464ac38d9.png)

sorry i'm bad in english. hope you understand T__T

**Comment by nightynight99** [comment]
can you add your pic? i'm not show what's part you mean

**Comment by njmlvr** [comment]
hereee. im not sure where to click on this page :(

**Comment by nightynight99** [comment]
i think i cant see your pic. can you send in my mail? dearmyboobooo@gmail.com

**Comment by muratalperen** [comment]
Hey @njmlvr. I will upload to chrome extension store after a minor update which I'll do today. Then there is a little time for review of this extension. So you will bring update in 1 or 2 day. Thanks for your attention.

**Comment by njmlvr** [comment]
alright noted! thank you so much 🤍
